# Generated by Django 4.1.6 on 2023-02-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_pic',
            field=models.ImageField(null=True, upload_to='category_pics'),
        ),
    ]
